### PR TITLE
J! 3.x compatible version; pack script is added; Missing string is added

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by cheryeong** [comment]
Thanks for the PR. Love the pack.sh script. Would you be able to create a separate PR for that? Preferably with changes to use the version number from profilepicture.xml and use that on the final zip file. Also update the creationDate with the current month & Year of the build?

J3! fixes has been commited separated.

Not going to add eclipse specific preference file.

**Comment by solomax** [comment]
It seems like I cannot create new PR
Could you please perform manual merge with this: https://github.com/solomax/profilepicture/commit/b46e8d667a423e8f707ce6dcd692b11c4da461a3 commit?

**Comment by cheryeong** [comment]
Running pack.sh on a Joomla directory zips all the Joomla content from /language/en-GB/* and /media/*. Need to separate it so that it ignore all files but profilepicture's.

Also, it's not detecting the version during my test. The resulting zip file name is pkg_profilepicture-.zip.

**Comment by solomax** [comment]
I'm a little bit confused
There is no "Joomla directory" in your git repo, as well as "/language/en-GB/*" and "/media/*" in your repo only contains necessary files.

I'll clone your repo and check the pack script one more time

**Comment by cheryeong** [comment]
Sorry, I should clarify that I'm doing this inside a working Joomla directory. That is the reason the bash script is zipping all the other files inside the /language and /media folder.

**Comment by solomax** [comment]
I'm afraid it will be impossible for me to test this :(
Maybe it is possible to separate the Joomla and the plugin? I believe this might both simplify .gitignore and script
I have prepared new PR and have tested it on your repo (fresh clone) everything seems to work as expected

**Comment by cheryeong** [comment]
I commited build.sh at beca9abc7a878024c45c2b442ec5530d7d7675ff based on your original pack.sh script. It uses git archive command which means you can run it on a Joomla directory. Thanks!

**Comment by solomax** [comment]
great :)
was happy to help :)

**Pull request closed without merging**
